apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

def versionName = {
    def stdout = new ByteArrayOutputStream()
    def errout = new ByteArrayOutputStream()
    try {
        exec {
            commandLine 'git', 'tag', '--points-at', 'HEAD'
            standardOutput = stdout
            errorOutput = errout
            ignoreExitValue = true
        }
    } catch (Exception ignored) {
        return "unknown-SNAPSHOT"
    }
    def tag = stdout.toString().trim()
    if (tag != null && !tag.isEmpty()) {
        return tag
    }
    def branchStream = new ByteArrayOutputStream()
    try {
        exec {
            commandLine 'git', 'rev-parse', '--abbrev-ref', 'HEAD'
            standardOutput = branchStream
            ignoreExitValue = true
        }
    } catch (Exception ignored) {
        return "unknown-SNAPSHOT"
    }
    def branch = branchStream.toString().trim().replace('/', '-')
    return "${branch}-SNAPSHOT"
}

android {
    compileSdkVersion rootProject.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        kotlinOptions.freeCompilerArgs += [
            '-module-name', "com.github.ChuckerTeam.Chucker.library-no-op",
            "-Xexplicit-api=strict"
        ]
    }

    buildFeatures {
        buildConfig = false
    }

    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
    }

    lintOptions {
        warningsAsErrors true
        abortOnError true
        // We don't want to impose RTL on consuming applications.
        disable 'RtlEnabled'
        // Don't fail build if some dependencies outdated
        disable 'GradleDependency'
    }
}

dependencies {
    api "com.squareup.okhttp3:okhttp:$okhttpVersion"
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
}

task androidSourcesJar(type: Jar) {
    archiveClassifier.set('sources')
    from android.sourceSets.main.java.srcDirs
}

afterEvaluate {
    publishing {
        publications {
            aar(MavenPublication) {
                groupId = 'com.meesho.android.chucker'
                artifactId = project.name
                version = versionName()
                from components.release
                artifact androidSourcesJar
            }
        }
    }
}

artifactory {
    contextUrl = "${JFROG_ARTIFACTORY_URL}"
    publish {
        repository {
            repoKey = versionName().endsWith('SNAPSHOT') ? "${SNAPSHOT_REPO_NAME}" : "${RELEASE_REPO_NAME}"
            username = "${JFROG_ARTIFACTORY_USERNAME}"
            password = "${JFROG_ARTIFACTORY_KEY}"
            maven = true
        }
        defaults {
            publications('aar')
            publishArtifacts = true
            publishPom = true
        }
    }
}

apply from: rootProject.file('gradle/kotlin-static-analysis.gradle')
